name: 01 Basics First Workflow

on:
  workflow_dispatch

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "Hello world"
      - name: Step2
        run: echo "hello world 2"
  job-2:

  job-3:
