name: 01 Basics First Workflow

on:
  repository_dispatch:
    types: [custom-event]

jobs:
  print-hello-world:
    runs-on: ubuntu-latest
    steps:
      - name: Print hello world
        run: echo "Hello world"

